import os
import sys
from sqlalchemy import *
from sqlalchemy.ext.declarative import declarative_base

#declarations

engine = create_engine('sqlite:///todo.db', echo = False)

metadata = MetaData(engine)

Base = declarative_base()
Base.metadata.bind = engine

class TodoList(Base):
	"""
	The class TodoList will be used to create a table that will store the information
	regarding the lists that will be entred by the user. For example, "Books to Read"
	"""
	__tablename__ = "todo_list"

	list_id = Column(Integer, primary_key=True) #to be autogenerated

	lists = Column(String(250), nullable=False) #list column
	

class Items(Base):
	"""
	The class Items will be used to create a table that will store the information
	regarding the items that will be entred by the user. For example, under "Books to Read"
	we have "Tom Jones", "Up from Slavery", and "1984"
	"""
	__tablename__ = "item_list"
	item_id = Column(Integer, primary_key=True) #item_id to be autogenerated
	list_id = Column(Integer, primary_key=False) #list_id this will be picked from the list_id @TodoList
	items = Column(String(250), nullable=False) #the items column
	

Base.metadata.create_all(engine) #command to create the tables
